In [1]:
print("Jay Ganesh")

Jay Ganesh


In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
sent=[
    'The glass of milk',
    'The glass of juice',
    'The cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'My videos are good'
]


In [5]:
sent

['The glass of milk',
 'The glass of juice',
 'The cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'My videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
## One host representation for every word
onehotrepr=[one_hot(word,voc_size) for word in sent]
onehotrepr

[[9887, 3411, 8942, 5220],
 [9887, 3411, 8942, 155],
 [9887, 3031, 8942, 1888],
 [4201, 9122, 2750, 3977, 6701],
 [4201, 9122, 2750, 3977, 135],
 [9384, 9887, 6677, 8942, 3942],
 [3390, 6675, 7700, 3977]]

In [10]:
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
#pad sequences are used because our length of word is of different size and we need to make it standardized for giving as an input to the model so we would be using pad_sequences for the task

sent_length=8 #Making sequenze length
embeddingdoc=pad_sequences(onehotrepr,padding='pre',maxlen=sent_length)#padding=pre to do padding at front post for end
print(embeddingdoc)


[[   0    0    0    0 9887 3411 8942 5220]
 [   0    0    0    0 9887 3411 8942  155]
 [   0    0    0    0 9887 3031 8942 1888]
 [   0    0    0 4201 9122 2750 3977 6701]
 [   0    0    0 4201 9122 2750 3977  135]
 [   0    0    0 9384 9887 6677 8942 3942]
 [   0    0    0    0 3390 6675 7700 3977]]


In [14]:
## Feature Representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.predict(embeddingdoc)

1/1 [==============================] - 0s 233ms/step


array([[[-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,
          0.02541799,  0.00700409, -0.04854337, -0.01243614,
          0.02034149, -0.00547621],
        [-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,
          0.02541799,  0.00700409, -0.04854337, -0.01243614,
          0.02034149, -0.00547621],
        [-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,
          0.02541799,  0.00700409, -0.04854337, -0.01243614,
          0.02034149, -0.00547621],
        [-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,
          0.02541799,  0.00700409, -0.04854337, -0.01243614,
          0.02034149, -0.00547621],
        [ 0.0348301 , -0.02694205,  0.01848651,  0.04304178,
          0.00905131, -0.01652312, -0.0038247 ,  0.00651341,
          0.01235535,  0.0499847 ],
        [-0.03138407, -0.01052625,  0.0415461 , -0.00592716,
         -0.03407419, -0.04374776,  0.04276693, -0.04295663,
         -0.02196797,  0.02779507],
        [-0.01182046, -0.01537228, -0.02460127, -0.0

In [19]:
embeddingdoc[0]

array([   0,    0,    0,    0, 9887, 3411, 8942, 5220])

In [20]:
model.predict(embeddingdoc[0])

1/1 [==============================] - 0s 55ms/step


array([[-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,  0.02541799,
         0.00700409, -0.04854337, -0.01243614,  0.02034149, -0.00547621],
       [-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,  0.02541799,
         0.00700409, -0.04854337, -0.01243614,  0.02034149, -0.00547621],
       [-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,  0.02541799,
         0.00700409, -0.04854337, -0.01243614,  0.02034149, -0.00547621],
       [-0.03348688, -0.00424453,  0.00033146,  0.0467342 ,  0.02541799,
         0.00700409, -0.04854337, -0.01243614,  0.02034149, -0.00547621],
       [ 0.0348301 , -0.02694205,  0.01848651,  0.04304178,  0.00905131,
        -0.01652312, -0.0038247 ,  0.00651341,  0.01235535,  0.0499847 ],
       [-0.03138407, -0.01052625,  0.0415461 , -0.00592716, -0.03407419,
        -0.04374776,  0.04276693, -0.04295663, -0.02196797,  0.02779507],
       [-0.01182046, -0.01537228, -0.02460127, -0.02761489,  0.00962524,
        -0.01986424, -0.01241066,  0.0011657 